
DROP TABLE IF EXISTS Aine CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS Arviointi CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Reseptilista CASCADE;
